[engine]
rate = 20                                   # 速率
duration = "20s"                            # 持续时间
cap = 3                                     # 客户端虚拟机数量
instant=1                                   # 每个批次发的交易数
wait="0s"                                   # 获取cap最大等待时间

[client]
script = "benchmark/ethereum/transfer/script.lua"   # 脚本
type = "eth"                                        # 区块链类型
config = "benchmark/ethereum/transfer/eth"          # 区块链SDK配置路径
plugin = "./eth.so"                                 # 插件路径

[client.options] # 客户端选项

[recorder.log]
dump=false
dir="./logs"
level="debug"

[recorder.csv]
dir="./csv"





